# The URL the site will be built for
base_url = "https://mefool.github.io"

compile_sass = true # Whether to automatically compile all Sass files in the sass directory
build_search_index = true # Whether to build a search index to be used later on by a JavaScript library

title = "bflog"

# theme # added
theme = "anpu-custom"

taxonomies = [
    {name = "categories" },
    {name = "tags", rss = false},

]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
anpu_menu_links = [
    { url = "$BASE_URL/", name = "home" },
    { url = "$BASE_URL/about/", name = "about" },
    { url = "$BASE_URL/tags/", name = "tags" },
    { url = "$BASE_URL/categories/", name = "cats" },
]
anpu_date_format = "%e %B %Y"
